# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/hima-common/setup-makefiles.sh

# ADSP
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/adsprpcd:system/bin/adsprpcd \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so

# DRM
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/qseecomd:system/bin/qseecomd \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so

# GPS
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
	  vendor/sharp/msm8994-common/proprietary/lib64/libgps.utils.so:system/lib64/libgps.utils.so \
	  vendor/sharp/msm8994-common/proprietary/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so \
	  vendor/sharp/msm8994-common/proprietary/lib64/libloc_core.so:system/lib64/libloc_core.so \
	  vendor/sharp/msm8994-common/proprietary/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so \
	  vendor/sharp/msm8994-common/proprietary/lib64/libloc_eng.so:system/lib64/libloc_eng.so \
	  vendor/sharp/msm8994-common/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
	  vendor/sharp/msm8994-common/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
	  vendor/sharp/msm8994-common/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	  vendor/sharp/msm8994-common/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
	  vendor/sharp/msm8994-common/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
	  vendor/sharp/msm8994-common/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so

# Graphics
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/hw/vulkan.msm8994.so:system/vendor/lib/hw/vulkan.msm8994.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libllvm-qgl.so:system/vendor/lib/libllvm-qgl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/hw/vulkan.msm8994.so:system/vendor/lib64/hw/vulkan.msm8994.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libbccQTI.so:system/vendor/lib64/libbccQTI.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libllvm-qgl.so:system/vendor/lib64/libllvm-qgl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libuiblur.so:system/vendor/lib64/libuiblur.so

# IPA
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/ipacm-diag:system/bin/ipacm-diag

# IR
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/cir_fw_update:system/bin/cir_fw_update \
	  vendor/sharp/msm8994-common/proprietary/etc/cir.img:system/etc/cir.img \
	  vendor/sharp/msm8994-common/proprietary/lib/hw/consumerir.default.so:system/lib/hw/consumerir.default.so \
	  vendor/sharp/msm8994-common/proprietary/lib64/hw/consumerir.default.so:system/lib64/hw/consumerir.default.so

# Listen
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/hw/sound_trigger.primary.msm8994.so:system/vendor/lib/hw/sound_trigger.primary.msm8994.so

# Media
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so

# Media firmware
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
	  vendor/sharp/msm8994-common/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

# Perf
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/energy-awareness:system/bin/energy-awareness \
	  vendor/sharp/msm8994-common/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
	  vendor/sharp/msm8994-common/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so

# Peripheral manager
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/pm-proxy:system/bin/pm-proxy \
	  vendor/sharp/msm8994-common/proprietary/bin/pm-service:system/bin/pm-service \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so

# Postprocessing
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libmm-als.so:system/vendor/lib64/libmm-als.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so

# QMI
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/irsc_util:system/bin/irsc_util \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so

# Radio
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/netmgrd:system/bin/netmgrd \
	  vendor/sharp/msm8994-common/proprietary/bin/qmuxd:system/bin/qmuxd \
	  vendor/sharp/msm8994-common/proprietary/bin/radish:system/bin/radish \
	  vendor/sharp/msm8994-common/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so

# Sensors
#PRODUCT_COPY_FILES += \
#	  vendor/sharp/msm8994-common/proprietary/lib64/hw/sensors.msm8994.so:system/lib64/hw/sensors.msm8994.so

# Thermal
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so

# Wifi
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/cnss_diag:system/bin/cnss_diag \
	  vendor/sharp/msm8994-common/proprietary/bin/cnss-daemon:system/bin/cnss-daemon

# Widevine
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
	  
# Keystore
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib64/hw/keystore.msm8994.so:system/vendor/lib64/hw/keystore.msm8994.so \
	  vendor/sharp/msm8994-common/proprietary/vendor/lib/hw/keystore.msm8994.so:system/vendor/lib/hw/keystore.msm8994.so

# Time services
PRODUCT_COPY_FILES += \
	  vendor/sharp/msm8994-common/proprietary/bin/time_daemon:system/bin/time_daemon

PRODUCT_PACKAGES += \
    libTimeService \
    libtime_genoff \
    TimeService
